fixtures:
  repositories:
    stdlib:        "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:        "git://github.com/puppet-community/puppet-extlib.git"
    foreman:       "git://github.com/theforeman/puppet-foreman.git"
    common:        "git://github.com/katello/puppet-common.git"
  symlinks:
    certs: "#{source_dir}"
