fixtures:
  repositories:
    extlib: "https://github.com/voxpupuli/puppet-extlib"
    foreman: "https://github.com/theforeman/puppet-foreman"
    openssl:
      repo: "https://github.com/ehelms/puppet-openssl"
      branch: "ca-password"
    redis: "https://github.com/voxpupuli/puppet-redis"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
