fixtures:
  repositories:
    concat:            "https://github.com/puppetlabs/puppetlabs-concat"
    extlib:            "https://github.com/voxpupuli/puppet-extlib"
    stdlib:            "https://github.com/puppetlabs/puppetlabs-stdlib"
