fixtures:
  repositories:
    stdlib:            "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:
      repo: 'git://github.com/puppet-community/puppet-extlib'
      ref:  'v0.11.3'
    foreman:           "git://github.com/theforeman/puppet-foreman.git"
    common:            "git://github.com/katello/puppet-common.git"
    trusted_ca:        "git://github.com/evenup/evenup-trusted_ca.git"
    concat:            "git://github.com/puppetlabs/puppetlabs-concat"
  symlinks:
    certs: "#{source_dir}"
