---
.puppet-lint.rc:
  extra_disabled_lint_checks:
    - arrow_on_right_operand_line
.travis.yml:
  beaker_sets:
  - centos7-64
  test_all_rvms: false
Rakefile:
  param_docs_pattern:
    - manifests/foreman_proxy_content.pp
    - manifests/init.pp
