---
# This file is managed centrally by modulesync
#   https://github.com/katello/foreman-installer-modulesync
rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.1
env:
  - PUPPET_VERSION=4.6 ONLY_OS=redhat-7-x86_64,centos-7-x86_64
matrix:
  fast_finish: true
bundler_args: --without system_tests development
sudo: false
